### PR TITLE
Add a `Key features` section to Ballerina track

### PR DESCRIPTION
**Pull request by praneesha**
Add a `Key features` section to Ballerina track

### CODE REVIEW

**Comment by praneesha** [comment]
@kytrinyx - Can you merge this PR, please?

**Comment by kytrinyx** [comment]
@praneesha Please take a look at the CI failure. The tool that the CI failure is referring to is documented here: https://exercism.org/docs/building/configlet

I am not on the Ballerina team. They are the ones who should review this and potentially offer suggestions for improvement.

**Comment by praneesha** [comment]
> @praneesha Please take a look at the CI failure. The tool that the CI failure is referring to is documented here: https://exercism.org/docs/building/configlet
> 
> I am not on the Ballerina team. They are the ones who should review this and potentially offer suggestions for improvement.

Sure. Thanks a lot.

**Comment by anupama-pathirage** [comment]
Looks good to merge. @ThisaruGuruge

**Review by ErikSchierboom — APPROVED** [review]

**Review by ThisaruGuruge — APPROVED** [review]

**Pull request merged**
