### PR TITLE
Ballerina Track Soft Launch

### PR DESCRIPTION
**Pull request by vordimous**
I think we are getting close to a set of exercises we can soft launch and then continue to improve and add to based on user feedback.

There are two exercises that need to be refactored due to the lack of external connectivity and timeout window. They are valuable examples of ballerina and I think they can be used if we rework or split them into smaller exercises. Can we leave them as WIP?
- "slug": "http-billion-dollar-question",
- "slug": "http-cake-is-a-lie",

### CODE REVIEW

**Comment by vordimous** [comment]
Once we can verify the db exercises are working with the necessary `platform-libs` we will have 16 of the 18 ready to go.

**Review by ErikSchierboom — APPROVED** [review]
> There are two exercises that need to be refactored due to the lack of external connectivity and timeout window. They are valuable examples of ballerina and I think they can be used if we rework or split them into smaller exercises. Can we leave them as WIP?

Yes that's fine.

> Once we can verify the db exercises are working with the necessary platform-libs we will have 16 of the 18 ready to go.

That sounds good. Once the soft launch has verified everything is working in order and we have 20+ exercises, we can do the official launch.

**Review by iHiD — APPROVED** [review]

**Comment by vordimous** [comment]
> That sounds good. Once the soft launch has verified everything is working in order and we have 20+ exercises, we can do the official launch.

Awesome! The remaining 10 exercises we have are a bit larger, so we could get a few smaller ones out of each. We can also consider the concepts and other features.

**Comment by ErikSchierboom** [comment]
> Awesome! The remaining 10 exercises we have are a bit larger, so we could get a few smaller ones out of each. We can also consider the concepts and other features.

I'd focus on just adding new practice exercises. Developing concepts is something that we're currently not focusing on. It is much more beneficial to have more practice exercises right now.

**Comment by vordimous** [comment]
> I'd focus on just adding new practice exercises. Developing concepts is something that we're currently not focusing on. It is much more beneficial to have more practice exercises right now.

Ok great, I will work with the team on this.

**Pull request merged**
