### PR TITLE
Ballerina/simplify hello world

### PR DESCRIPTION
**Pull request by son1112**
-~includes `configlet fmt` changes to `config.json` and `config/maintainer.json`~ _Update: submitted those in separate PR._

### CODE REVIEW

**Comment by son1112** [comment]
#4707

**Comment by kytrinyx** [comment]
@son1112 Would you mind moving the `configlet fmt` changes to a separate PR? I can approve that separately, and then this PR will be much more focused and easier to review for the Ballerina team.

**Comment by kytrinyx** [comment]
@exercism/ballerina Would you have a chance to review and discuss this change?

The short story is that it's intended to make the hello world exercise mostly about ensuring that everything is wired up correctly. It gets auto-approved, and then people move on to exercises that will actually require them to learn some ballerina.

**Comment by kytrinyx** [comment]
@vinok88 Are you waiting for someone else to merge? I'm not sure what your team's process is here.

**Pull request merged**
