### PR TITLE
Reformat exercise config files

### PR DESCRIPTION
**Pull request by kytrinyx**
This runs the `bin/configlet fmt --update` command to
reformat the exercise configs.

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Comment by vordimous** [comment]
@kytrinyx I added #156 to address this for all new exercises. I ran the configlet fmt command and it wanted to remove all of the `"icon"` attributes. Is there a better place for me to put them?

**Comment by kytrinyx** [comment]
Oh, the `icon` attribute is a great question. @ErikSchierboom @ee7 do you know where `icon` is meant to live?

**Comment by ErikSchierboom** [comment]
> Oh, the icon attribute is a great question. @ErikSchierboom @ee7 do you know where icon is meant to live?

I think this is a bug. I'll fix it tomorrow.

**Comment by ErikSchierboom** [comment]
PR submitted: https://github.com/exercism/configlet/pull/716

**Comment by kytrinyx** [comment]
Thank you @ee7.

**Comment by kytrinyx** [comment]
I've redone the formatting and force pushed to this branch to update the PR.

**Pull request merged**
