### PR TITLE
Add mechanism to skip tests

### PR DESCRIPTION
**Pull request by glennj**
I chose perl because CI runs on Linux and MacOS, and sed has different behaviour around `-i` between GNU and BSD.

If it looks OK, I'll add more exercises to the PR.

https://lib.ballerina.io/ballerina/test/0.0.0#TestConfig

attn: @ErikSchierboom

### CODE REVIEW

**Comment by glennj** [comment]
Another approach to take, instead of `enable: false`, is `groups: ["skipped"]`, but then to run the tests without running the skipped group requires specifying so explicitly:
```sh
bal test --disable-group skipped
```

**Review by ErikSchierboom — APPROVED** [review]
Nice work! Could you update the other exercises too?

**Comment by glennj** [comment]
I've updated the recent exercises, but I haven't (yet) touched the "original" exercises.

**Comment by ErikSchierboom** [comment]
That's fine!

**Review by ErikSchierboom — APPROVED** [review]
Awesome job. Now I have to update all my PRs 😁

**Pull request merged**
