### PR TITLE
Fixing CI as part of a general update to the Ballerina swan-lake version

### LINKED ISSUE #123: Fix CI
This repository's `main` branch currently does not pass all CI checks.
This makes detecting issues in PRs harder and might result in a broken track, and so is an important thing to fix.

The following CI workflows are currently failing:

https://github.com/exercism/ballerina/runs/3066717991
https://github.com/exercism/ballerina/runs/3066717957
https://github.com/exercism/ballerina/runs/3066717942

## Tracking

https://github.com/exercism/v3-launch/issues/55

### PR DESCRIPTION
**Pull request by vordimous**
Fixes #123

The PR removes outdated samples (to be added once they can be updated) and updates the Ci process such that it passes.

- use java 11 _ AJ Danelz
- fix the test runner for the practice samples _ AJ Danelz
- fix ci _ AJ Danelz
- update hello world _ AJ Danelz
- Remove outdated samples _ AJ Danelz

### CODE REVIEW

**Comment by vordimous** [comment]
Hi @ErikSchierboom, I am the head of DevRel at WSO2 and work with the team behind Ballerina. I am hoping to resolve all of these issues and get this repo back into a state where the language can be offered on Exercism again. You can see my [Excercism Profile](https://exercism.org/profiles/vordimous). 

I figured this issue #123 was a good place to start but any other guidance you can offer would be appreciated.

**Comment by ErikSchierboom** [comment]
> Hi @ErikSchierboom, I am the head of DevRel at WSO2 and work with the team behind Ballerina. I am hoping to resolve all of these issues and get this repo back into a state where the language can be offered on Exercism again. You can see my [Excercism Profile](https://exercism.org/profiles/vordimous).

That's great. Thanks a lot. 

As for this PR: I noticed that you deleted a lot of files, all of which actually _should_ not be deleted I think. What was your reasoning?

**Comment by vordimous** [comment]
> As for this PR: I noticed that you deleted a lot of files, all of which actually _should_ not be deleted, I think. What was your reasoning?

The files I deleted were just the exercise files. The Ballerina programming language had its first major milestone release, and the structure of the language changed a lot. I will have to go back through each exercise and rewrite them in the new structure. 

I figured it would be easiest to tackle one problem at a time and didn't want to comment out a bunch of code.

**Comment by vordimous** [comment]
There are a lot of issues in this repo and a lot of new exercises that we want to add. I am looking to spend as much time as necessary to get this back on the site for people to learn. Once the Ci is working, what should I focus on next, or do I need to solve all of the repo issues before the language can be added back?

**Comment by vordimous** [comment]
I have updated the config.json to exclude the exercises.

**Comment by ErikSchierboom** [comment]
> The files I deleted were just the exercise files. The Ballerina programming language had its first major milestone release, and the structure of the language changed a lot. I will have to go back through each exercise and rewrite them in the new structure.

Okay. whatever works best for you.

> There are a lot of issues in this repo and a lot of new exercises that we want to add. I am looking to spend as much time as necessary to get this back on the site for people to learn. Once the Ci is working, what should I focus on next, or do I need to solve all of the repo issues before the language can be added back?

We have documentation for new tracks: https://exercism.org/docs/building/tracks/new Basically, what you should do is to follow the steps listed there. Ping me for any PRs you do.

**Comment by ErikSchierboom** [comment]
Oh, could you restore the exercises? People will have already submitted solutions to those exercises so they can't be just removed. What you can do is to add a `"status"` field with value `"deprecated"`, but if I'm hearing you correctly, you want to rewrite them and so I'd probably not do that.

**Comment by vordimous** [comment]
> Oh, could you restore the exercises? People will have already submitted solutions to those exercises so they can't be just removed. What you can do is to add a `"status"` field with value `"deprecated"`, but if I'm hearing you correctly, you want to rewrite them and so I'd probably not do that.

Yeah, I don't mind adding them back. Some might be deprecated so i can go that route as i find them. I got all of the [GH Actions](https://github.com/vordimous/ballerina/actions/workflows/ci.yml) to pass. If you think the only thing remaining is to fix the existing exercises I will work on those. Is there anything else in the repo I need to update?

**Comment by vordimous** [comment]
> We have documentation for new tracks: https://exercism.org/docs/building/tracks/new Basically, what you should do is to follow the steps listed there. Ping me for any PRs you do.

I will review this onboarding and see what might be missing.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
> I will review this onboarding and see what might be missing. Do you want me to keep updating this PR or separate out these changes?

Please do small, invididual PRs per step (and per exercise).

**Comment by ErikSchierboom** [comment]
Thanks for this!

**Comment by ErikSchierboom** [comment]
Oh whoops, I clicked too soon. The exercises are still there.
It's no problem, but maybe you could add them back at some point (with the same data like uuids).

**Comment by vordimous** [comment]
Ok, for this PR I will fix all of the CI issues and remove the broken exercises, keeping only the hello-world default. I will add back the other exercises in separate PRs with the exact same data & UUIDs. Hopefully, it won't take a long time but that way the changes are separate.

**Comment by vordimous** [comment]
> Thanks for this!

Thank you for making Exercism! I am hoping to leverage it heavily to get new people to learn Ballerina.

**Comment by ErikSchierboom** [comment]
Lovely!

**Pull request merged**
